import { sanitizeSeedRecord } from "./equipment.logic";
import { EquipmentRecord } from "./equipment.types";

const EQUIPMENT_SEED_DATA: EquipmentRecord[] = [
  {
    id: "eq-treadmill-01",
    name: "Treadmill A1",
    category: "cardio",
    brandModel: "Life Fitness Integrity+",
    serialNumber: "LF-A1-44211",
    purchaseDate: "2024-01-10",
    purchaseCost: 6800,
    warrantyExpiryDate: "2027-01-10",
    condition: "good",
    maintenanceFrequency: "monthly",
    lastMaintenanceDate: "2026-02-05",
    nextMaintenanceDue: "2026-03-05",
    assignedArea: "Cardio Zone - Floor 1",
    notes: "High usage during evening peak hours.",
    isActive: true,
    maintenanceLogs: [
      {
        id: "log-treadmill-01-1",
        date: "2026-02-05",
        type: "routine",
        description: "Belt alignment and motor inspection",
        cost: 120,
        performedBy: "FitTech Services",
        nextDueDate: "2026-03-05",
      },
      {
        id: "log-treadmill-01-2",
        date: "2026-01-05",
        type: "repair",
        description: "Replaced worn running belt",
        cost: 340,
        performedBy: "FitTech Services",
        nextDueDate: "2026-02-05",
      },
    ],
    auditTrail: [
      {
        id: "audit-treadmill-01-1",
        date: "2026-02-05",
        action: "Maintenance Logged",
        description: "Routine maintenance completed",
        performedBy: "FitTech Services",
      },
    ],
  },
  {
    id: "eq-treadmill-02",
    name: "Treadmill B2",
    category: "cardio",
    brandModel: "Technogym Excite Run",
    serialNumber: "TG-B2-55109",
    purchaseDate: "2023-06-02",
    purchaseCost: 7200,
    warrantyExpiryDate: "2026-06-02",
    condition: "needs_maintenance",
    maintenanceFrequency: "monthly",
    lastMaintenanceDate: "2026-01-10",
    nextMaintenanceDue: "2026-02-10",
    assignedArea: "Cardio Zone - Floor 1",
    notes: "Reports of unusual motor noise.",
    isActive: true,
    maintenanceLogs: [
      {
        id: "log-treadmill-02-1",
        date: "2026-01-10",
        type: "routine",
        description: "Deck lubrication and calibration",
        cost: 110,
        performedBy: "FitTech Services",
        nextDueDate: "2026-02-10",
      },
    ],
    auditTrail: [
      {
        id: "audit-treadmill-02-1",
        date: "2026-02-12",
        action: "Condition Updated",
        description: "Condition changed to needs maintenance",
        performedBy: "Owner",
      },
    ],
  },
  {
    id: "eq-rower-01",
    name: "Rower C4",
    category: "cardio",
    brandModel: "Concept2 RowErg",
    serialNumber: "C2-C4-12005",
    purchaseDate: "2022-08-12",
    purchaseCost: 1450,
    warrantyExpiryDate: "2026-08-12",
    condition: "out_of_order",
    maintenanceFrequency: "quarterly",
    lastMaintenanceDate: "2025-10-15",
    nextMaintenanceDue: "2026-01-15",
    assignedArea: "Functional Zone - Floor 1",
    notes: "Monitor intermittently powers off.",
    isActive: true,
    maintenanceLogs: [
      {
        id: "log-rower-01-1",
        date: "2025-10-15",
        type: "repair",
        description: "Cable and chain inspection",
        cost: 95,
        performedBy: "Internal Technician",
        nextDueDate: "2026-01-15",
      },
    ],
    auditTrail: [
      {
        id: "audit-rower-01-1",
        date: "2026-02-18",
        action: "Marked Out of Order",
        description: "Removed from daily usage until monitor replacement",
        performedBy: "Admin",
      },
    ],
  },
  {
    id: "eq-squat-rack-01",
    name: "Squat Rack D1",
    category: "strength",
    brandModel: "Rogue Monster Lite",
    serialNumber: "RG-D1-7721",
    purchaseDate: "2021-04-20",
    purchaseCost: 2400,
    warrantyExpiryDate: "2027-04-20",
    condition: "good",
    maintenanceFrequency: "quarterly",
    lastMaintenanceDate: "2025-12-15",
    nextMaintenanceDue: "2026-03-15",
    assignedArea: "Strength Zone - Floor 2",
    notes: "Anchor bolts re-checked each quarter.",
    isActive: true,
    maintenanceLogs: [
      {
        id: "log-squat-rack-01-1",
        date: "2025-12-15",
        type: "routine",
        description: "Frame and bolt torque check",
        cost: 60,
        performedBy: "Internal Technician",
        nextDueDate: "2026-03-15",
      },
    ],
    auditTrail: [
      {
        id: "audit-squat-rack-01-1",
        date: "2025-12-15",
        action: "Maintenance Logged",
        description: "Quarterly check completed",
        performedBy: "Internal Technician",
      },
    ],
  },
  {
    id: "eq-cable-machine-01",
    name: "Cable Crossover E2",
    category: "strength",
    brandModel: "Matrix Magnum",
    serialNumber: "MX-E2-9982",
    purchaseDate: "2020-09-10",
    purchaseCost: 5300,
    warrantyExpiryDate: "2026-03-15",
    condition: "good",
    maintenanceFrequency: "quarterly",
    lastMaintenanceDate: "2025-11-20",
    nextMaintenanceDue: "2026-02-20",
    assignedArea: "Strength Zone - Floor 2",
    notes: "Warranty expiring soon, monitor pulley wear closely.",
    isActive: true,
    maintenanceLogs: [
      {
        id: "log-cable-machine-01-1",
        date: "2025-11-20",
        type: "routine",
        description: "Pulley track cleaning and cable test",
        cost: 150,
        performedBy: "FitTech Services",
        nextDueDate: "2026-02-20",
      },
    ],
    auditTrail: [
      {
        id: "audit-cable-machine-01-1",
        date: "2025-11-20",
        action: "Maintenance Logged",
        description: "Quarterly check completed",
        performedBy: "FitTech Services",
      },
    ],
  },
  {
    id: "eq-dumbbell-set-01",
    name: "Dumbbell Set 2.5kg-50kg",
    category: "free_weights",
    brandModel: "Eleiko Premium",
    serialNumber: "",
    purchaseDate: "2019-03-01",
    purchaseCost: 9800,
    warrantyExpiryDate: "2029-03-01",
    condition: "good",
    maintenanceFrequency: "yearly",
    lastMaintenanceDate: "2025-06-01",
    nextMaintenanceDue: "2026-06-01",
    assignedArea: "Free Weights Zone",
    notes: "Re-rack compliance remains high.",
    isActive: true,
    maintenanceLogs: [
      {
        id: "log-dumbbell-set-01-1",
        date: "2025-06-01",
        type: "routine",
        description: "Grip wear inspection and weight calibration",
        cost: 210,
        performedBy: "Internal Technician",
        nextDueDate: "2026-06-01",
      },
    ],
    auditTrail: [
      {
        id: "audit-dumbbell-set-01-1",
        date: "2025-06-01",
        action: "Maintenance Logged",
        description: "Annual free-weight calibration completed",
        performedBy: "Internal Technician",
      },
    ],
  },
  {
    id: "eq-yoga-mat-rack-01",
    name: "Yoga Mat Rack",
    category: "accessories",
    brandModel: "Custom Steel Rack",
    serialNumber: "CS-YMR-010",
    purchaseDate: "2018-07-11",
    purchaseCost: 450,
    warrantyExpiryDate: "2023-07-11",
    condition: "good",
    maintenanceFrequency: "yearly",
    lastMaintenanceDate: "2025-01-10",
    nextMaintenanceDue: "2026-01-10",
    assignedArea: "Studio Hall - Floor 1",
    notes: "Retained for backup class inventory.",
    isActive: false,
    maintenanceLogs: [
      {
        id: "log-yoga-mat-rack-01-1",
        date: "2025-01-10",
        type: "replacement",
        description: "Replaced damaged support frame",
        cost: 90,
        performedBy: "Internal Technician",
        nextDueDate: "2026-01-10",
      },
    ],
    auditTrail: [
      {
        id: "audit-yoga-mat-rack-01-1",
        date: "2025-12-01",
        action: "Retired",
        description: "Moved to retired accessory inventory",
        performedBy: "Owner",
      },
    ],
  },
];

export const getSeedEquipment = (): EquipmentRecord[] =>
  EQUIPMENT_SEED_DATA.map((record) => sanitizeSeedRecord(record));
