-- AlterTable
ALTER TABLE "gym_settings" ADD COLUMN     "features" JSONB DEFAULT '[]',
ADD COLUMN     "hero_badge_text" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "trainers_cta_label" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "workouts_cta_label" TEXT NOT NULL DEFAULT '',
ALTER COLUMN "gym_name" SET DEFAULT 'My Gym',
ALTER COLUMN "tag_line" SET DEFAULT '',
ALTER COLUMN "address" SET DEFAULT '',
ALTER COLUMN "phone" SET DEFAULT '',
ALTER COLUMN "email" SET DEFAULT '',
ALTER COLUMN "logo" SET DEFAULT '',
ALTER COLUMN "description" SET DEFAULT '',
ALTER COLUMN "favicon" SET DEFAULT '',
ALTER COLUMN "primary_color" SET DEFAULT '#22c55e',
ALTER COLUMN "secondary_color" SET DEFAULT '#4ade80',
ALTER COLUMN "background_color" SET DEFAULT '#0a0a0a',
ALTER COLUMN "text_color" SET DEFAULT '#ffffff',
ALTER COLUMN "hero_title" SET DEFAULT '',
ALTER COLUMN "hero_subtitle" SET DEFAULT '',
ALTER COLUMN "hero_cta_primary" SET DEFAULT '',
ALTER COLUMN "hero_cta_secondary" SET DEFAULT '',
ALTER COLUMN "features_title" SET DEFAULT '',
ALTER COLUMN "features_subtitle" SET DEFAULT '',
ALTER COLUMN "classes_title" SET DEFAULT '',
ALTER COLUMN "classes_subtitle" SET DEFAULT '',
ALTER COLUMN "trainers_title" SET DEFAULT '',
ALTER COLUMN "trainers_subtitle" SET DEFAULT '',
ALTER COLUMN "workouts_title" SET DEFAULT '',
ALTER COLUMN "workouts_subtitle" SET DEFAULT '',
ALTER COLUMN "pricing_title" SET DEFAULT '',
ALTER COLUMN "pricing_subtitle" SET DEFAULT '',
ALTER COLUMN "footer_tagline" SET DEFAULT '',
ALTER COLUMN "app_showcase_title" SET DEFAULT '',
ALTER COLUMN "app_showcase_subtitle" SET DEFAULT '',
ALTER COLUMN "cta_title" SET DEFAULT '',
ALTER COLUMN "cta_subtitle" SET DEFAULT '',
ALTER COLUMN "cta_button_label" SET DEFAULT '',
ALTER COLUMN "classes_bg_image" SET DEFAULT '',
ALTER COLUMN "cta_bg_image" SET DEFAULT '',
ALTER COLUMN "features_bg_image" SET DEFAULT '',
ALTER COLUMN "hero_bg_image" SET DEFAULT '',
ALTER COLUMN "pricing_bg_image" SET DEFAULT '',
ALTER COLUMN "trainers_bg_image" SET DEFAULT '',
ALTER COLUMN "workouts_bg_image" SET DEFAULT '';
