import { sanitizeCostRecord } from "./costs.logic";
import { CostRecordInput } from "./costs.types";

const COST_SEED_DATA: CostRecordInput[] = [
  {
    id: "cost-rent-2026-02",
    title: "Main Facility Rent",
    category: "rent",
    costType: "fixed",
    amount: 3250,
    taxAmount: 0,
    paymentMethod: "bank",
    billingPeriod: "monthly",
    costDate: "2026-02-01",
    dueDate: "2026-02-03",
    paidDate: "2026-02-02",
    paymentStatus: "paid",
    budgetGroup: "Facilities",
    vendor: "Skyline Properties",
    referenceNumber: "RENT-2026-02",
    notes: "Monthly lease payment for gym premises.",
    createdBy: "Owner",
    status: "active",
    createdAt: "2026-02-01",
    updatedAt: "2026-02-02",
    auditTrail: [
      {
        id: "audit-rent-2026-02-1",
        date: "2026-02-01",
        action: "Created",
        description: "Cost entry created",
        performedBy: "Owner",
      },
    ],
  },
  {
    id: "cost-salaries-2026-02",
    title: "Staff Salaries - February",
    category: "salaries",
    costType: "fixed",
    amount: 13800,
    taxAmount: 0,
    paymentMethod: "bank",
    billingPeriod: "monthly",
    costDate: "2026-02-05",
    dueDate: "2026-02-05",
    paidDate: "2026-02-05",
    paymentStatus: "paid",
    budgetGroup: "Payroll",
    vendor: "Payroll Transfer",
    referenceNumber: "SAL-2026-02",
    notes: "Includes coaches and reception team payouts.",
    createdBy: "Admin",
    status: "active",
    createdAt: "2026-02-05",
    updatedAt: "2026-02-05",
    auditTrail: [
      {
        id: "audit-salaries-2026-02-1",
        date: "2026-02-05",
        action: "Created",
        description: "Cost entry created",
        performedBy: "Admin",
      },
    ],
  },
  {
    id: "cost-utilities-electric-2026-02",
    title: "Electricity Bill",
    category: "utilities",
    costType: "variable",
    amount: 980,
    taxAmount: 53,
    paymentMethod: "online",
    billingPeriod: "monthly",
    costDate: "2026-02-10",
    dueDate: "2026-02-25",
    paidDate: "",
    paymentStatus: "pending",
    budgetGroup: "Utilities",
    vendor: "City Electric",
    referenceNumber: "UTIL-ELEC-2026-02",
    notes: "Higher usage during evening classes.",
    createdBy: "Admin",
    status: "active",
    createdAt: "2026-02-10",
    updatedAt: "2026-02-10",
    auditTrail: [
      {
        id: "audit-electric-2026-02-1",
        date: "2026-02-10",
        action: "Created",
        description: "Cost entry created",
        performedBy: "Admin",
      },
    ],
  },
  {
    id: "cost-maintenance-2026-q1",
    title: "Quarterly Equipment Servicing",
    category: "maintenance",
    costType: "variable",
    amount: 640,
    taxAmount: 21,
    paymentMethod: "bank",
    billingPeriod: "quarterly",
    costDate: "2026-02-12",
    dueDate: "2026-02-20",
    paidDate: "",
    paymentStatus: "pending",
    budgetGroup: "Maintenance",
    vendor: "FitTech Services",
    referenceNumber: "MAIN-Q1-2026",
    notes: "Preventive servicing for cardio machines.",
    createdBy: "Admin",
    status: "active",
    createdAt: "2026-02-12",
    updatedAt: "2026-02-12",
    auditTrail: [
      {
        id: "audit-maintenance-q1-1",
        date: "2026-02-12",
        action: "Created",
        description: "Cost entry created",
        performedBy: "Admin",
      },
    ],
  },
  {
    id: "cost-software-2026-02",
    title: "Gym Software Subscription",
    category: "software",
    costType: "fixed",
    amount: 295,
    taxAmount: 0,
    paymentMethod: "card",
    billingPeriod: "monthly",
    costDate: "2026-02-15",
    dueDate: "2026-02-15",
    paidDate: "2026-02-15",
    paymentStatus: "paid",
    budgetGroup: "Systems",
    vendor: "GymCRM Pro",
    referenceNumber: "SFT-2026-02",
    notes: "Membership and booking platform.",
    createdBy: "Owner",
    status: "active",
    createdAt: "2026-02-15",
    updatedAt: "2026-02-15",
    auditTrail: [
      {
        id: "audit-software-2026-02-1",
        date: "2026-02-15",
        action: "Created",
        description: "Cost entry created",
        performedBy: "Owner",
      },
    ],
  },
  {
    id: "cost-marketing-2026-02",
    title: "Local Campaign Promotion",
    category: "marketing",
    costType: "variable",
    amount: 520,
    taxAmount: 0,
    paymentMethod: "online",
    billingPeriod: "one_time",
    costDate: "2026-02-18",
    dueDate: "2026-02-18",
    paidDate: "",
    paymentStatus: "pending",
    budgetGroup: "Growth",
    vendor: "Meta Ads",
    referenceNumber: "MKT-2026-02",
    notes: "Two-week membership acquisition campaign.",
    createdBy: "Owner",
    status: "active",
    createdAt: "2026-02-18",
    updatedAt: "2026-02-18",
    auditTrail: [
      {
        id: "audit-marketing-2026-02-1",
        date: "2026-02-18",
        action: "Created",
        description: "Cost entry created",
        performedBy: "Owner",
      },
    ],
  },
  {
    id: "cost-equipment-2026-01",
    title: "Stationary Bike Replacement",
    category: "equipment",
    costType: "variable",
    amount: 2200,
    taxAmount: 99,
    paymentMethod: "bank",
    billingPeriod: "one_time",
    costDate: "2026-01-22",
    dueDate: "2026-01-30",
    paidDate: "2026-01-28",
    paymentStatus: "paid",
    budgetGroup: "Assets",
    vendor: "Life Fitness",
    referenceNumber: "EQP-2026-01",
    notes: "Replacement for worn-out spin bike.",
    createdBy: "Owner",
    status: "active",
    createdAt: "2026-01-22",
    updatedAt: "2026-01-28",
    auditTrail: [
      {
        id: "audit-equipment-2026-01-1",
        date: "2026-01-22",
        action: "Created",
        description: "Cost entry created",
        performedBy: "Owner",
      },
    ],
  },
  {
    id: "cost-rent-2026-01",
    title: "Main Facility Rent",
    category: "rent",
    costType: "fixed",
    amount: 3250,
    taxAmount: 0,
    paymentMethod: "bank",
    billingPeriod: "monthly",
    costDate: "2026-01-01",
    dueDate: "2026-01-03",
    paidDate: "2026-01-02",
    paymentStatus: "paid",
    budgetGroup: "Facilities",
    vendor: "Skyline Properties",
    referenceNumber: "RENT-2026-01",
    notes: "Monthly lease payment for gym premises.",
    createdBy: "Owner",
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-01-02",
    auditTrail: [
      {
        id: "audit-rent-2026-01-1",
        date: "2026-01-01",
        action: "Created",
        description: "Cost entry created",
        performedBy: "Owner",
      },
    ],
  },
  {
    id: "cost-other-insurance-2026",
    title: "Business Insurance",
    category: "other",
    costType: "fixed",
    amount: 1800,
    taxAmount: 0,
    paymentMethod: "bank",
    billingPeriod: "yearly",
    costDate: "2026-01-03",
    dueDate: "2026-01-31",
    paidDate: "2026-01-20",
    paymentStatus: "paid",
    budgetGroup: "Compliance",
    vendor: "SafeShield Insurance",
    referenceNumber: "INS-2026",
    notes: "Annual gym operations insurance policy.",
    createdBy: "Owner",
    status: "active",
    createdAt: "2026-01-03",
    updatedAt: "2026-01-20",
    auditTrail: [
      {
        id: "audit-insurance-2026-1",
        date: "2026-01-03",
        action: "Created",
        description: "Cost entry created",
        performedBy: "Owner",
      },
    ],
  },
  {
    id: "cost-software-archived-2025",
    title: "Legacy POS Subscription",
    category: "software",
    costType: "fixed",
    amount: 245,
    taxAmount: 0,
    paymentMethod: "card",
    billingPeriod: "monthly",
    costDate: "2025-12-14",
    dueDate: "2025-12-14",
    paidDate: "2025-12-14",
    paymentStatus: "paid",
    budgetGroup: "Systems",
    vendor: "LegacyPOS",
    referenceNumber: "POS-2025-12",
    notes: "Archived after platform migration.",
    createdBy: "Admin",
    status: "archived",
    createdAt: "2025-12-14",
    updatedAt: "2026-01-04",
    auditTrail: [
      {
        id: "audit-software-legacy-1",
        date: "2026-01-04",
        action: "Archived",
        description: "Cost entry archived",
        performedBy: "Admin",
      },
      {
        id: "audit-software-legacy-2",
        date: "2025-12-14",
        action: "Created",
        description: "Cost entry created",
        performedBy: "Admin",
      },
    ],
  },
  {
    id: "cost-overdue-supplier-2026-01",
    title: "Locker Room Supplies",
    category: "maintenance",
    costType: "variable",
    amount: 340,
    taxAmount: 12,
    paymentMethod: "cash",
    billingPeriod: "monthly",
    costDate: "2026-01-12",
    dueDate: "2026-01-20",
    paidDate: "",
    paymentStatus: "overdue",
    budgetGroup: "Consumables",
    vendor: "CleanFlow Supplies",
    referenceNumber: "SUP-2026-01",
    notes: "Awaiting owner approval.",
    createdBy: "Admin",
    status: "active",
    createdAt: "2026-01-12",
    updatedAt: "2026-01-12",
    auditTrail: [
      {
        id: "audit-overdue-1",
        date: "2026-01-12",
        action: "Created",
        description: "Cost entry created",
        performedBy: "Admin",
      },
    ],
  },
];

export const COST_SEED = COST_SEED_DATA.map((record) => sanitizeCostRecord(record));
